title: The Dyer Lab
author: Kelly A. Dyer

url: "https://kse-uga.github.io"
baseurl: "/kdyerlab.github.io"

remote_theme: peterdesmet/petridish@3.2

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

colors:
  links: "##cccc3a"
  banner: "##333300"
  footer: "#cc3401"

font_serif: false
rounded_corners: false
posts_on_home: 0
